spring.application.name=evaluacion
server.port=8084
spring.datasource.url=jjdbc:mysql://mysql_evaluacion:3306/universidad_backend?createDatabaseIfNotExist=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexiones Feign
asignaturas.service.url=http://entorno_asignaturas:8080

# --- CONFIGURACIÓN FASE 4: TIMEOUTS ---
# Tiempo máximo para establecer conexión (3 segundos)
spring.cloud.openfeign.client.config.default.connectTimeout=3000

# Tiempo máximo para esperar la respuesta (5 segundos)
spring.cloud.openfeign.client.config.default.readTimeout=5000