server.port=8083
spring.application.name=sistema-biblioteca

# Configuración de conexión a la base de datos exclusiva
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql_biblioteca:3306/biblioteca_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:desarrollador}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logs del sistema
logging.level.cl.duoc.sistema_biblioteca=INFO

# Swagger UI / OpenAPI estructurado
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Conexiones Feign y Timeouts
estudiantes.service.url=http://entorno_programacion1:8081
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000