version: '3.8'

services:
  # --- MÓDULO ASIGNATURAS ---
  db-asignaturas:
    image: mysql:8
    container_name: db-asignaturas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3314:3306"
    volumes:
      - persistencia_db_asignaturas:/var/lib/mysql
    networks:
      - red_asignaturas

  ms-asignaturas:
    build: ./asignaturas
    container_name: ms-asignaturas
    ports:
      - "8080:8080"
    depends_on:
      - db-asignaturas
    networks:
      - red_asignaturas

  # --- MÓDULO ESTUDIANTES ---
  db-estudiantes:
    image: mysql:8
    container_name: db-estudiantes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3306:3306"
    volumes:
      - persistencia_db_estudiantes:/var/lib/mysql
    networks:
      - red_estudiantes

  ms-estudiantes:
    build: ./estudiantes
    container_name: ms-estudiantes
    ports:
      - "8081:8081"
    depends_on:
      - db-estudiantes
    networks:
      - red_estudiantes

  # --- MÓDULO PROFESORES ---
  db-profesores:
    image: mysql:8
    container_name: db-profesores
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3307:3306"
    volumes:
      - persistencia_db_profesores:/var/lib/mysql
    networks:
      - red_profesores

  ms-profesores:
    build: ./profesores
    container_name: ms-profesores
    ports:
      - "8082:8082"
    depends_on:
      - db-profesores
    networks:
      - red_profesores

  # --- MÓDULO EVALUACIÓN ---
  db-evaluacion:
    image: mysql:8
    container_name: db-evaluacion
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3309:3306"
    volumes:
      - persistencia_db_evaluacion:/var/lib/mysql
    networks:
      - red_evaluacion

  ms-evaluacion:
    build: ./evaluacion
    container_name: ms-evaluacion
    ports:
      - "8084:8084"
    depends_on:
      - db-evaluacion
    networks:
      - red_evaluacion

  # --- MÓDULO CARRERA ---
  db-carrera:
    image: mysql:8
    container_name: db-carrera
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3315:3306"
    volumes:
      - persistencia_db_carrera:/var/lib/mysql
    networks:
      - red_carrera

  ms-carrera:
    build: ./carrera
    container_name: ms-carrera
    ports:
      - "8089:8089"
    depends_on:
      - db-carrera
    networks:
      - red_carrera

  # --- MÓDULO PAGOS ---
  db-pagos:
    image: mysql:8
    container_name: db-pagos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3316:3306"
    volumes:
      - persistencia_db_pagos:/var/lib/mysql
    networks:
      - red_pagos

  ms-pagos:
    build: ./pagos
    container_name: ms-pagos
    ports:
      - "8090:8090"
    depends_on:
      - db-pagos
    networks:
      - red_pagos

# --- MÓDULO BIBLIOTECA ---
  db-biblioteca:
    image: mysql:8
    container_name: db-biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3308:3306"
    volumes:
      - persistencia_db_biblioteca:/var/lib/mysql
    networks:
      - red_biblioteca

  ms-biblioteca:
    build: ./biblioteca
    container_name: ms-biblioteca
    ports:
      - "8083:8083"
    depends_on:
      - db-biblioteca
    networks:
      - red_biblioteca

  # --- MÓDULO INSCRIPCIONES ---
  db-inscripciones:
    image: mysql:8
    container_name: db-inscripciones
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3310:3306"
    volumes:
      - persistencia_db_inscripciones:/var/lib/mysql
    networks:
      - red_inscripciones

  ms-inscripciones:
    build: ./inscripciones
    container_name: ms-inscripciones
    ports:
      - "8085:8085"
    depends_on:
      - db-inscripciones
    networks:
      - red_inscripciones

  # --- MÓDULO BECAS ---
  db-becas:
    image: mysql:8
    container_name: db-becas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3311:3306"
    volumes:
      - persistencia_db_becas:/var/lib/mysql
    networks:
      - red_becas

  ms-becas:
    build: ./becas
    container_name: ms-becas
    ports:
      - "8086:8086"
    depends_on:
      - db-becas
    networks:
      - red_becas

  # --- MÓDULO SALAS ---
  db-salas:
    image: mysql:8
    container_name: db-salas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3312:3306"
    volumes:
      - persistencia_db_salas:/var/lib/mysql
    networks:
      - red_salas

  ms-salas:
    build: ./salas
    container_name: ms-salas
    ports:
      - "8087:8087"
    depends_on:
      - db-salas
    networks:
      - red_salas

  # --- MÓDULO ASISTENCIA ---
  db-asistencia:
    image: mysql:8
    container_name: db-asistencia
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3313:3306"
    volumes:
      - persistencia_db_asistencia:/var/lib/mysql
    networks:
      - red_asistencia

  ms-asistencia:
    build: ./asistencia
    container_name: ms-asistencia
    ports:
      - "8088:8088"
    depends_on:
      - db-asistencia
    networks:
      - red_asistencia

# DEFINICIÓN GLOBAL DE REDES Y VOLÚMENES
networks:
  red_asignaturas:
    driver: bridge
  red_estudiantes:
    driver: bridge
  red_profesores:
    driver: bridge
  red_evaluacion:
    driver: bridge
  red_carrera:
    driver: bridge
  red_pagos:
    driver: bridge
  red_biblioteca:
    driver: bridge
  red_inscripciones:
    driver: bridge
  red_becas:
    driver: bridge
  red_salas:
    driver: bridge
  red_asistencia:
    driver: bridge

volumes:
  persistencia_db_asignaturas:
  persistencia_db_estudiantes:
  persistencia_db_profesores:
  persistencia_db_evaluacion:
  persistencia_db_carrera:
  persistencia_db_pagos:
  persistencia_db_biblioteca:
  persistencia_db_inscripciones:
  persistencia_db_becas:
  persistencia_db_salas:
  persistencia_db_asistencia: