version: '3.8'

x-mysql-env: &mysql_env
  MYSQL_ROOT_PASSWORD: clave_maestra_root
  MYSQL_USER: desarrollador
  MYSQL_PASSWORD: password_seguro_123

services:
  
  # --- MÓDULO ESTUDIANTES ---
  db-estudiantes:
    image: mysql:8.0
    container_name: mysql_estudiantes  
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: estudiantes_db
    ports: ["3306:3306"]
    networks:
      red_estudiantes:
        aliases:
          - mysql_servidor 
    volumes: [persistencia_db_estudiantes:/var/lib/mysql]
  workspace-java: 
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_programacion1
    ports: ["8081:8081"]
    depends_on: [db-estudiantes]
    networks: [red_estudiantes, red_universidad]
    environment:
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=red_universidad
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./gestion-estudiante:/app"]
    working_dir: /app

  # --- MÓDULO PROFESORES ---
  db-profesor:
    image: mysql:8.0
    container_name: mysql_profesor
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: profesores_db
    ports: ["3307:3306"]
    networks: [red_profesores]
    volumes: [persistencia_db_profesor:/var/lib/mysql]

  workspace-profesor:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_profesor
    ports: ["8082:8082"]
    depends_on: [db-profesor]
    networks: [red_profesores, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./gestion-profesor:/app"]
    working_dir: /app

  # --- MÓDULO BIBLIOTECA ---
  db-biblioteca:
    image: mysql:8.0
    container_name: mysql_biblioteca
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: biblioteca_db
    ports: ["3308:3306"]
    networks: [red_biblioteca]
    volumes: [persistencia_db_biblioteca:/var/lib/mysql]

  workspace-biblioteca:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_biblioteca
    ports: ["8083:8083"]
    depends_on: [db-biblioteca]
    networks: [red_biblioteca, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./sistema-biblioteca:/app"]
    working_dir: /app

  # --- MÓDULO EVALUACIÓN ---
  db-evaluacion:
    image: mysql:8.0
    container_name: mysql_evaluacion
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: evaluacion_db
    ports: ["3309:3306"]
    networks: [red_evaluacion]
    volumes: [persistencia_db_evaluacion:/var/lib/mysql]

  workspace-evaluacion:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_evaluacion
    ports: ["8084:8084"]
    depends_on: [db-evaluacion]
    networks: [red_evaluacion, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./sistema-evaluacion:/app"]
    working_dir: /app

  # --- MÓDULO INSCRIPCIONES ---
  db-inscripcion:
    image: mysql:8.0
    container_name: mysql_inscripcion
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: inscripciones_db
    ports: ["3310:3306"]
    networks: [red_inscripcion]
    volumes: [persistencia_db_inscripcion:/var/lib/mysql]

  workspace-inscripcion:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_inscripcion
    ports: ["8085:8085"]
    depends_on: [db-inscripcion]
    networks: [red_inscripcion, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./sistema-inscripcion:/app"]
    working_dir: /app

  # --- MÓDULO BECAS ---
  db-beca:
    image: mysql:8.0
    container_name: mysql_beca
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: becas_db
    ports: ["3311:3306"]
    networks: [red_becas]
    volumes: [persistencia_db_beca:/var/lib/mysql]

  workspace-beca:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_beca
    ports: ["8086:8086"]
    depends_on: [db-beca]
    networks: [red_becas, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./becas:/app"]
    working_dir: /app

  # --- MÓDULO SALAS ---
  db-sala:
    image: mysql:8.0
    container_name: mysql_sala
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: salas_db
    ports: ["3312:3306"]
    networks: [red_salas]
    volumes: [persistencia_db_sala:/var/lib/mysql]

  workspace-sala:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_sala
    ports: ["8087:8087"]
    depends_on: [db-sala]
    networks: [red_salas, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./gestion-sala:/app"]
    working_dir: /app

  # --- MÓDULO ASISTENCIA ---
  db-asistencia:
    image: mysql:8.0
    container_name: mysql_asistencia
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: asistencia_db
    ports: ["3317:3306"]
    networks: [red_asistencia]
    volumes: [persistencia_db_asistencia:/var/lib/mysql]

  workspace-asistencia:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_asistencia
    ports: ["8088:8088"]
    depends_on: [db-asistencia]
    networks: [red_asistencia, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./sistema-asistencia:/app"]
    working_dir: /app

  # --- MÓDULO ASIGNATURAS ---
  db-asignaturas:
    image: mysql:8.0
    container_name: mysql_asignaturas
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: asignaturas_db
    ports: ["3314:3306"]
    networks: [red_asignaturas]
    volumes: [persistencia_db_asignaturas:/var/lib/mysql]

  workspace-asignaturas:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_asignaturas
    ports: ["8080:8080"]
    depends_on: [db-asignaturas]
    networks: [red_asignaturas, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./asignaturas:/app"]
    working_dir: /app

  # --- MÓDULO CARRERA ---
  db-carrera:
    image: mysql:8.0
    container_name: mysql_carrera
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: carrera_db
    ports: ["3315:3306"]
    networks: [red_carrera]
    volumes: [persistencia_db_carrera:/var/lib/mysql]

  workspace-carrera:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_carrera
    ports: ["8089:8089"]
    depends_on: [db-carrera]
    networks: [red_carrera, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./carrera:/app"]
    working_dir: /app

  # --- MÓDULO PAGOS ---
  db-pagos:
    image: mysql:8.0
    container_name: mysql_pagos
    environment:
      <<: *mysql_env
      MYSQL_DATABASE: pagos_db
    ports: ["3316:3306"]
    networks: [red_pagos]
    volumes: [persistencia_db_pagos:/var/lib/mysql]

  workspace-pagos:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_pagos
    ports: ["8090:8090"]
    depends_on: [db-pagos]
    networks: [red_pagos, red_universidad]
    command: bash -c "sleep 60; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./pagos:/app"]
    working_dir: /app

  # --- API GATEWAY CENTRAL ---
  workspace-gateway:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_gateway
    ports: ["8099:8099"]
    networks:
      - red_universidad
      - red_estudiantes  
    command: bash -c "sleep 75; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes: ["./ms-gateway:/app"]
    working_dir: /app

networks:
  red_universidad:
    driver: bridge
  red_asignaturas:
    driver: bridge
  red_becas:
    driver: bridge
  red_carrera:
    driver: bridge
  red_profesores:
    driver: bridge
  red_salas:
    driver: bridge
  red_pagos:
    driver: bridge
  red_asistencia:
    driver: bridge
  red_biblioteca:
    driver: bridge
  red_evaluacion:
    driver: bridge
  red_inscripcion:
    driver: bridge
  red_estudiantes:
    driver: bridge

volumes:
  persistencia_db_asignaturas:
  persistencia_db_beca:
  persistencia_db_carrera:
  persistencia_db_estudiantes:
  persistencia_db_profesor:
  persistencia_db_sala:
  persistencia_db_pagos:
  persistencia_db_asistencia:
  persistencia_db_biblioteca:
  persistencia_db_evaluacion:
  persistencia_db_inscripcion: