services:
  db-pagos:
    image: mysql:8.0
    container_name: mysql_pagos
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: pagos_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3316:3306"
    networks:
      - red_pagos
      - red_universidad
    volumes:
      - persistencia_db_pagos:/var/lib/mysql

  workspace-pagos:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_pagos
    ports:
      - "8090:8090"
    depends_on:
      - db-pagos
    networks:
      - red_pagos
      - red_universidad
    command: bash -c "sleep 15; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes:
      - ./:/app
    working_dir: /app

networks:
  red_pagos:
    driver: bridge
  red_universidad:
    external: true
    name: proyecto_red_universidad  

volumes:
  persistencia_db_pagos: