services:
  # ------------------------------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL PARA EL SISTEMA DE PAGOS
  # ------------------------------------------------------------------
  db-pagos:
    image: mysql:8.0
    container_name: mysql_pagos
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: universidad_backend
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3316:3306"  # Puerto DB Host
    networks:
      - red_pagos
    volumes:
      - persistencia_db_pagos:/var/lib/mysql

  # ------------------------------------------------------------------
  # CONTENEDOR 2: EL ENTORNO DE TRABAJO JAVA/SPRING BOOT
  # ------------------------------------------------------------------
  workspace-pagos:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_pagos
    ports:
      - "8090:8090" # El microservicio correrá en el puerto 8090
    depends_on:
      - db-pagos
    networks:
      - red_pagos
    command: tail -f /dev/null
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml

networks:
  red_pagos:
    driver: bridge

volumes:
  persistencia_db_pagos: