server:
  port: 8088

spring:
  application:
    name: SISTEMA-ASISTENCIA
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql_asistencia:3306/asistencia_db?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:desarrollador}
    password: ${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

logging:
  level:
    cl:
      duoc:
        sistema_asistencia: INFO

# Conexiones Feign Clientes existentes
inscripciones:
  service:
    url: http://entorno_inscripcion:8085
salas:
  service:
    url: http://entorno_sala:8087
estudiantes:
  service:
    url: http://32.198.93.76:8081

# Configuración Swagger / OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# ⚙️ Registro en tu Eureka de AWS
eureka:
  client:
    service-url:
      defaultZone: http://3.86.130.217:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 54.91.52.2