server.port=8088
spring.application.name=sistema-asistencia

# Configuración de conexión a la base de datos (con fallback local/docker)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql_asistencia:3306/asistencia_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:desarrollador}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Niveles de Log asignados por el estándar de la asignatura
logging.level.cl.duoc.sistema_asistencia=INFO

# Conexiones Feign
inscripciones.service.url=http://entorno_inscripcion:8085
salas.service.url=http://entorno_sala:8087

# --- TIMEOUTS DE OPENFEIGN ---
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Swagger UI / OpenAPI de acuerdo al profesor
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
estudiantes.service.url=http://32.198.93.76:8081