server.port=8087
spring.application.name=gestion-sala

# Configuración de conexión dinámica a la base de datos (Corregido Host y DB)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db-sala:3306/salas_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:desarrollador}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.cl.duoc.gestion_sala=INFO

# OpenAPI / Swagger UI para Salas (IE 3.2.1)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# --- CONFIGURACIÓN FASE 4: TIMEOUTS OPENFEIGN ---
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000