spring.application.name=evaluacion
server.port=8084

# Configuración de conexión a la base de datos (Entorno Docker)
spring.datasource.url=jdbc:mysql://mysql_evaluacion:3306/evaluacion_db?createDatabaseIfNotExist=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logs estandarizados por paquete
logging.level.cl.duoc.evaluacion=INFO

# Conexiones Feign Clientes
asignaturas.service.url=http://entorno_asignaturas:8080
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Swagger UI / OpenAPI (Siguiendo el estilo del profesor)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html