server:
  port: 8084

spring:
  application:
    name: EVALUACION
  
  datasource:
    url: jdbc:mysql://mysql_evaluacion:3306/evaluacion_db?createDatabaseIfNotExist=true
    username: desarrollador
    password: password_seguro_123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

logging:
  level:
    cl:
      duoc:
        evaluacion: INFO

# Conexiones Feign Clientes
asignaturas:
  service:
    url: http://entorno_asignaturas:8080

# Swagger UI / OpenAPI al estilo del profesor
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html


eureka:
  client:
    service-url:
      defaultZone: http://3.86.130.217:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 54.91.52.2