spring.application.name=gestion-estudiante
server.port=8081


# Usa la variable de Docker, y si corres afuera en Ubuntu, respalda a localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3311/estudiantes_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:desarrollador}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_seguro_123}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN FASE 4: TIMEOUTS ---
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Habilitar SpringDoc y Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html