server:
  port: 8081

spring:
  application:
    name: GESTION-ESTUDIANTE
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql_servidor:3306/estudiantes_db?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:desarrollador}
    password: ${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

# Habilitar SpringDoc y Swagger UI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# ⚙️ Registro en tu Eureka de AWS
eureka:
  client:
    service-url:
      defaultZone: http://3.86.130.217:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 54.91.52.2