spring.application.name=gestion-estudiante
server.port=8081

# CAMBIO: Usamos el nombre del contenedor 'mysql_servidor' y la DB 'universidad_backend'
spring.datasource.url=jdbc:mysql://mysql_servidor:3306/universidad_backend?createDatabaseIfNotExist=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN FASE 4: TIMEOUTS ---
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000