services:
  db-beca:
    image: mysql:8.0
    container_name: mysql_beca
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: becas_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3311:3306"
    networks:
      - red_becas
      - red_universidad
    volumes:
      - persistencia_db_beca:/var/lib/mysql

  workspace-beca:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_becas  
    ports:
      - "8086:8086"
    depends_on:
      - db-beca
    networks:
      - red_becas
      - red_universidad
    command: bash -c "sleep 15; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes:
      - ./:/app
    working_dir: /app

networks:
  red_becas:
    driver: bridge
  red_universidad:
    external: true
    name: proyecto_red_universidad 

volumes:
  persistencia_db_beca: