spring.application.name=gestion_profesor
server.port=8082


# Usa esta línea para correrlo en tu terminal (sin el #)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/universidad_backend?createDatabaseIfNotExist=true

# Deja esta línea comentada (con el #) por si algún día decides meter el código Java a Docker
# spring.datasource.url=jdbc:mysql://mysql_servidor:3306/universidad_backend

# Credenciales definidas previamente en el docker-compose

spring.datasource.username=root
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
