server:
  port: 8090

spring:
  application:
    name: MS-PAGOS  
  
  datasource:
    url: jdbc:mysql://mysql_pagos:3306/pagos_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: desarrollador
    password: password_seguro_123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

logging:
  level:
    cl.duoc.pagos: INFO

estudiantes:
  service:
    url: ${ESTUDIANTES_SERVICE_URL:http://entorno_estudiante:8081}
becas:
  service:
    url: ${BECAS_SERVICE_URL:http://entorno_becas:8086}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs/MS-PAGOS 
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://3.86.130.217:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 54.91.52.2 