spring.application.name=pagos
server.port=8090

# Configuración de base de datos con el puerto de Pagos (3316)
spring.datasource.url=jdbc:mysql://127.0.0.1:3316/universidad_backend?createDatabaseIfNotExist=true

spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true