server.port=8090
spring.application.name=ms-pagos

# Configuración de conexión a la base de datos con fallback local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pagos_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.cl.duoc.pagos=INFO

# Conexiones Dinámicas Feign mediante properties
estudiantes.service.url=${ESTUDIANTES_SERVICE_URL:http://localhost:8081}
becas.service.url=${BECAS_SERVICE_URL:http://localhost:8086}

# --- TIMEOUTS DE FEIGN ---
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Swagger UI / OpenAPI de la Asignatura
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html