services:
  db-carrera:
    image: mysql:8.0
    container_name: mysql_carrera
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: carrera_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3315:3306"  
    networks:
      - red_carrera
      - red_universidad
    volumes:
      - persistencia_db_carrera:/var/lib/mysql

  workspace-carrera:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_carrera
    ports:
      - "8089:8089"
    depends_on:
      - db-carrera
    networks:
      - red_carrera
      - red_universidad
    command: bash -c "sleep 15; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes:
      - ./:/app
    working_dir: /app

networks:
  red_carrera:
    driver: bridge
  red_universidad:
    external: true
    name: proyecto_red_universidad 

volumes:
  persistencia_db_carrera: