services:
  db-asistencia:
    image: mysql:8.0
    container_name: mysql_asistencia
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: asistencia_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3317:3306"
    networks:
      - red_asistencia
      - red_universidad
    volumes:
      - persistencia_db_asistencia:/var/lib/mysql

  workspace-asistencia:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_asistencia
    ports:
      - "8088:8088"
    depends_on:
      - db-asistencia
    networks:
      - red_asistencia
      - red_universidad
    command: bash -c "sleep 15; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes:
      - ./:/app
    working_dir: /app

networks:
  red_asistencia:
    driver: bridge
  red_universidad:
    external: true
    name: proyecto_red_universidad  

volumes:
  persistencia_db_asistencia: