server:
  port: 8086

spring:
  application:
    name: MS-BECAS  
  datasource:
    url: jdbc:mysql://mysql_beca:3306/becas_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: desarrollador
    password: password_seguro_123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    compatibility-verifier:
      enabled: false
    inetutils:
      preferred-networks:
        - 172.
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

logging:
  level:
    cl.duoc.beca: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs/MS-BECAS  
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://3.86.130.217:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 54.91.52.2  