services:
  db-profesor:
    image: mysql:8.0
    container_name: mysql_profesor
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: profesores_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3307:3306" 
    networks:
      - red_profesores
      - red_universidad
    volumes:
      - persistencia_db_profesor:/var/lib/mysql

  workspace-profesor:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_profesor
    ports:
      - "8082:8082"
    depends_on:
      - db-profesor
    networks:
      - red_profesores
      - red_universidad
    command: bash -c "sleep 15; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes:
      - ./:/app
    working_dir: /app
  
networks:
  red_profesores:
    driver: bridge  
  red_universidad:
    external: true
    name: proyecto_red_universidad  

volumes:
  persistencia_db_profesor: