spring:
  application:
    name: asignaturas
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql_asignaturas:3306/asignaturas_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:desarrollador}
    password: ${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# URLs de Microservicios externos
profesores:
  service:
    url: ${PROFESORES_SERVICE_URL:http://entorno_profesor:8082}
carrera:
  service:
    url: ${CARRERA_SERVICE_URL:http://entorno_carrera:8089}