services:
  db-biblioteca:
    image: mysql:8.0
    container_name: mysql_biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3308:3306"
    networks:
      - red_biblioteca
      - red_universidad
    volumes:
      - persistencia_db_biblioteca:/var/lib/mysql

  workspace-biblioteca:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_biblioteca
    ports:
      - "8083:8083"
    depends_on:
      - db-biblioteca
    networks:
      - red_biblioteca
      - red_universidad
   
    command: bash -c "sleep 15; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes:
      - ./:/app
    working_dir: /app

networks:
  red_biblioteca:
    driver: bridge
  red_universidad:
    external: true
    name: proyecto_red_universidad 

volumes:
  persistencia_db_biblioteca: