services:
  # ------------------------------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL PARA EL SISTEMA DE BIBLIOTECA
  # ------------------------------------------------------------------
  db-biblioteca:
    image: mysql:8.0
    container_name: mysql_biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: biblioteca_db  # <-- CORREGIDO: Base de datos única
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3308:3306"
    networks:
      - red_biblioteca
    volumes:
      - persistencia_db_biblioteca:/var/lib/mysql

  # ------------------------------------------------------------------
  # CONTENEDOR 2: EL ENTORNO DE TRABAJO JAVA/SPRING BOOT
  # ------------------------------------------------------------------
  workspace-biblioteca:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_biblioteca
    ports:
      - "8083:8083"
    depends_on:
      - db-biblioteca
    networks:
      - red_biblioteca
      - red_universidad  # Agregada para habilitar las peticiones Feign salientes a Estudiantes
    command: tail -f /dev/null
    volumes:
      - ./sistema-biblioteca:/app # CORREGIDO: Apunta a la carpeta del módulo de biblioteca

networks:
  red_biblioteca:
    driver: bridge
  red_universidad:
    driver: bridge

volumes:
  persistencia_db_biblioteca: