spring.application.name=sistema-inscripcion
server.port=8085

# CORREGIDO: Conector dinámico para la Base de Datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3310/inscripciones_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:desarrollador}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivar el verificador estricto de versiones de Spring Cloud
spring.cloud.compatibility-verifier.enabled=false

# CORREGIDO: Apuntar dinámicamente a Estudiantes en Localhost si corres por fuera
estudiantes.service.url=${ESTUDIANTES_URL:http://127.0.0.1:8081}
asignaturas.service.url=${ASIGNATURAS_URL:http://127.0.0.1:8080}

# --- CONFIGURACIÓN FASE 4: TIMEOUTS ---
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# --- CONFIGURACIÓN FASE 3: SWAGGER ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html