services:
  # -----------------------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL
  # -----------------------------------------------------------
  db-estudiantes:
    image: mysql:8.0
    container_name: mysql_servidor
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: estudiantes_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3311:3306"
    networks:
      - red_estudiantes # CORREGIDO: Red específica para aislar este módulo
    volumes:
      - persistencia_db_estudiantes:/var/lib/mysql # Sincronizado con el global

  # -----------------------------------------------------------
  # CONTENEDOR 2: EL ENTORNO DE TRABAJO JAVA/SPRING BOOT
  # -----------------------------------------------------------
  workspace-java:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_programacion1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_servidor:3306/estudiantes_db?createDatabaseIfNotExist=true
    ports:
      - "8081:8081"
    depends_on:
      - db-estudiantes
    networks:
      - red_estudiantes   # Red privada con su base de datos
      - red_universidad   # Red global para comunicarse con otros microservicios
    command: tail -f /dev/null
    volumes:
      - .:/app # CORREGIDO: Apunta a la carpeta correcta del proyecto
    working_dir: /app

networks:
  red_estudiantes:
    driver: bridge
  red_universidad:
    driver: bridge

volumes:
  persistencia_db_estudiantes: