services:
  db-sala:
    image: mysql:8.0
    container_name: mysql_sala
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: salas_db
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3313:3306"
    networks:
      - red_salas
      - red_universidad
    volumes:
      - persistencia_db_sala:/var/lib/mysql

  workspace-sala:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_sala
    ports:
      - "8087:8087"
    depends_on:
      - db-sala
    networks:
      - red_salas
      - red_universidad 
    command: bash -c "sleep 15; mvn spring-boot:run -Dmaven.test.skip=true -DskipTests"
    volumes:
      - ./:/app
    working_dir: /app

networks:
  red_salas:
    driver: bridge
  red_universidad:
    external: true
    name: proyecto_red_universidad 

volumes:
  persistencia_db_sala: